# Generated by Django 5.0.2 on 2024-02-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='fname',
        ),
    ]
