# Generated by Django 5.0.2 on 2024-03-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactinformation',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='commentormessage',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='lastname',
            new_name='lname',
        ),
    ]
