# Generated by Django 5.0.2 on 2024-03-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_register_data_alter_contactinformation_fname'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unameoremail', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=20)),
            ],
        ),
    ]
