# Generated by Django 5.0.2 on 2024-03-05 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_login_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_data',
        ),
    ]
