# Generated by Django 5.0.2 on 2024-03-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_register_data_mobilenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_Data',
        ),
    ]
