# Generated by Django 5.0.2 on 2024-03-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_delete_register_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('mobilenumber', models.IntegerField()),
                ('userpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
