# Generated by Django 5.0.2 on 2024-03-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_register_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register_Data',
            new_name='RegisterData',
        ),
    ]
