# Generated by Django 5.0.2 on 2024-03-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_rename_register_data_registerdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdata',
            old_name='username',
            new_name='uname',
        ),
    ]
