# Generated by Django 5.0.2 on 2024-03-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_rename_username_registerdata_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdata',
            old_name='uname',
            new_name='username',
        ),
    ]
