# Generated by Django 5.0.2 on 2024-03-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_rename_uname_registerdata_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('mobilenumber', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterData',
        ),
    ]
