# Generated by Django 5.0.2 on 2024-03-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_registerdata1_delete_registerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname1', models.CharField(max_length=50)),
                ('productprice1', models.IntegerField()),
                ('productname2', models.CharField(max_length=50)),
                ('productprice2', models.IntegerField()),
                ('productname3', models.CharField(max_length=50)),
                ('productprice3', models.IntegerField()),
                ('productname4', models.CharField(max_length=50)),
                ('productprice4', models.IntegerField()),
                ('productname5', models.CharField(max_length=50)),
                ('productprice5', models.IntegerField()),
                ('productname6', models.CharField(max_length=50)),
                ('productprice6', models.IntegerField()),
                ('productname7', models.CharField(max_length=50)),
                ('productprice7', models.IntegerField()),
                ('productname8', models.CharField(max_length=50)),
                ('productprice8', models.IntegerField()),
                ('productname9', models.CharField(max_length=50)),
                ('productprice9', models.IntegerField()),
                ('productname10', models.CharField(max_length=50)),
                ('productprice10', models.IntegerField()),
                ('productname11', models.CharField(max_length=50)),
                ('productprice11', models.IntegerField()),
                ('productname12', models.CharField(max_length=50)),
                ('productprice12', models.IntegerField()),
            ],
        ),
    ]
