# Generated by Django 5.0.2 on 2024-03-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_shopproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname10',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname11',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname12',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname2',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname3',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname4',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname5',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname6',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname7',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname8',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productname9',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice10',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice11',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice12',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice2',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice3',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice4',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice5',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice6',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice7',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice8',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='productprice9',
        ),
    ]
