# Generated by Django 5.0.2 on 2024-03-08 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_remove_shopproduct_productname10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopProduct',
        ),
    ]
