# Generated by Django 5.0.2 on 2024-03-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_delete_shopproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname1', models.CharField(max_length=50)),
                ('productprice1', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
