# Generated by Django 5.0.2 on 2024-03-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_cartinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartinfo',
            name='productquantity',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='producttotal',
            field=models.CharField(default=50, max_length=10),
        ),
    ]
