# Generated by Django 5.0.2 on 2024-03-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_cartinfo_productquantity_alter_cartinfo_producttotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='productquantity',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
