# Generated by Django 5.0.2 on 2024-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_alter_cartinfo_producttotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='productquantity',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
